### ISSUE TITLE
IDAT not found 

### ISSUE THREAD

**Issue by whecrane** [freeseek/gtc2vcf#27]
Hi freeseek,
      Thank you for your help yesterday and I installed the gtc2vcf successfully. But when I convert idat to gtc, the IDAT always not found at the location. I tried many times but can't solve it.  I checked the bpm and egt, I am sure they are right:
Chip Prefix (Guess),InfiniumPsychArray-24v1-1
I don't know why the idat not found, my idat files just like this:
GSM3096512_200687150051_R01C01_Grn.idat
GSM3096512_200687150051_R01C01_Red.idat

This is the log:
 ArrayAnalysis.NormToGenCall.CLI.App[0]
      [10:25:21 2352]: Crawling /media/EXTend2018/Wanghe2019/GEO/GSE113093/GSE113093_RAW for samples ...
info: ArrayAnalysis.NormToGenCall.CLI.App[0]
      [10:25:21 3578]: Number of samples to process: 103
info: ArrayAnalysis.NormToGenCall.Services.NormToGenCallSvc[0]
      [10:25:21 3714]: 
      Starting processing...
      Manifest file: /media/EXTend2018/Wanghe2019/GEO/GSE113093/InfiniumPsychArray-24v1-1_A1.bpm
      Cluster file: /media/EXTend2018/Wanghe2019/GEO/GSE113093/InfiniumPsychArray-24v1-1_A1_ClusterFile.egt
      Include file: 
      Output directory: /media/EXTend2018/Wanghe2019/GEO/GSE113093
      GenCall score cutoff: 0.15
      GenTrain ID: 3
      Gender Estimate Settings: 
                      Version: 2
                      MinAutosomalLoci : 100
                      MaxAutosomalLoci : 10000
                      MinXLoci : 20
                      MinYLoci : 20
                      AutosomalCallRateThreshold : 0.97
                      YIntensityThreshold : 0.3
                      XIntensityThreshold : 0.9
                      XHetRateThreshold : 0.1
      Output Settings: 
                      Output GTC: True
                      Output PED: False
                          PED tab delmited: False
                          PED use customer strand: False
      Number of threads: 1
      Buffer size: 131072
              
info: ArrayAnalysis.NormToGenCall.Services.NormToGenCallSvc[0]
[49m: ArrayAnalysis.NormToGenCall.Services.NormToGenCallSvc[0]
      [12:33:32 8929]: Failed to normalize or gencall - GSM3096512_200687150051_R01C01: IDAT not found at location: /media/EXTend2018/Wanghe2019/GEO/GSE113093/GSE113093_RAW/GSM3096512_200687150051_Red.idat
   at ArrayAnalysis.NormToGenCall.Services.SampleNormToGenCallSvc.LoadIdat(String idatPath, Manifest manifest) in /src/ArrayAnalysis.NormToGenCall.Services/Services/SampleNormToGenCallSvc.cs:line 63
   at ArrayAnalysis.NormToGenCall.Services.SampleNormToGenCallSvc.Normalize(NormalizationBase normAlg, Manifest manifest, Byte[] transformLookups, Boolean needGreen, Boolean needRed, SampleData sample, String[] includeLociNames) in /src/ArrayAnalysis.NormToGenCall.Services/Services/SampleNormToGenCallSvc.cs:line 106
   at ArrayAnalysis.NormToGenCall.Services.NormToGenCallSvc.<>c__DisplayClass7_0.<Run>b__2(SampleData sample) in /src/ArrayAnalysis.NormToGenCall.Services/Services/NormToGenCallSvc.cs:line 113
...There are many idat files fault like this. 

Best wishes,
Crane

**Comment by freeseek** [comment]
If you read the error message:
```
 [12:33:32 8929]: Failed to normalize or gencall - GSM3096512_200687150051_R01C01: IDAT not found at location: /media/EXTend2018/Wanghe2019/GEO/GSE113093/GSE113093_RAW/GSM3096512_200687150051_Red.idat
```
It shows that iaap-cli is looking for file `GSM3096512_200687150051_Red.idat` rather than file `GSM3096512_200687150051_R01C01_Red.idat`. How did it get to look for that? Well, someone at Illumina made the beautiful assumption that IDAT files are named `xxx_xxx_Grn.idat` and `xxx_xxx_Red.idat` and someone from NCBI GEO made the beautiful assumption that it is okay to rename IDAT files.

You put the two things together and that's what you get, unfortunately. I mostly blame Illumina here though.
